# Generated by Django 6.0.3 on 2026-03-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrawdata',
            name='record_type',
            field=models.CharField(choices=[('page_info', '페이지 정보'), ('candidate_link', '후보 링크')], db_index=True, default='candidate_link', max_length=30),
        ),
        migrations.AddField(
            model_name='crawlrawdata',
            name='unique_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='crawlrawdata',
            name='item_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='crawlrawdata',
            name='page_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='crawlrawdata',
            index=models.Index(fields=['target', 'record_type'], name='crawling_cr_target__7917a2_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlrawdata',
            index=models.Index(fields=['source_url'], name='crawling_cr_source__b071b1_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlrawdata',
            index=models.Index(fields=['item_url'], name='crawling_cr_item_ur_e1fde9_idx'),
        ),
    ]
