# Generated by Django 6.0.3 on 2026-03-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0003_alter_crawltarget_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawljoblog',
            name='command_name',
            field=models.CharField(default='scheduled_crawl', max_length=100),
        ),
        migrations.AlterField(
            model_name='crawlrawdata',
            name='record_type',
            field=models.CharField(choices=[('page_info', '페이지 정보'), ('candidate_link', '후보 링크'), ('review', '리뷰')], db_index=True, default='review', max_length=30),
        ),
        migrations.AlterField(
            model_name='crawltarget',
            name='target_type',
            field=models.CharField(choices=[('search', '검색 페이지'), ('product', '상품 상세 페이지')], default='product', max_length=20),
        ),
    ]
