server {
    listen 80;
    server_name _;

    client_max_body_size 20M;

    add_header Content-Security-Policy "default-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://product-review-statics.s3.amazonaws.com https://product-review-statics.s3.ap-northeast-2.amazonaws.com; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://product-review-statics.s3.amazonaws.com https://product-review-statics.s3.ap-northeast-2.amazonaws.com; connect-src 'self' https://cdn.jsdelivr.net; img-src 'self' data: https://product-review-statics.s3.amazonaws.com https://product-review-statics.s3.ap-northeast-2.amazonaws.com https://product-review-medium.s3.amazonaws.com https://product-review-medium.s3.ap-northeast-2.amazonaws.com; font-src 'self' data: https://product-review-statics.s3.amazonaws.com https://product-review-statics.s3.ap-northeast-2.amazonaws.com;" always;

    location /ai/ {
        proxy_pass http://fastapi-server:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        proxy_pass http://drf-web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
