# Generated by Django 6.0.3 on 2026-04-02 05:35

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_gateway', '0001_initial'),
        ('reviews', '0002_alter_review_options_alter_reviewai_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='reviews.review')),
            ],
        ),
    ]
