# Generated by Django 6.0.3 on 2026-03-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_alter_reviewbookmark_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_key', models.CharField(max_length=255, unique=True)),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
