# Generated by Django 6.0.3 on 2026-03-26 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_crawlrawdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrawlRawData',
        ),
    ]
