# Generated by Django 6.0.3 on 2026-04-02 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('reviews', '0002_alter_review_options_alter_reviewai_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewai',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reviewimage',
            options={},
        ),
        migrations.AddField(
            model_name='review',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='삭제 일시'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='삭제 여부'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='products.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewai',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
